sudo: required
language: node_js
node_js:
  - "10"
services:
  - docker
before_install:
  - docker build -t n23space/docker-react -f Dockerfile.dev .
script:
  - docker run n23space/docker-react npm run test -- --coverage